name: my-actions
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: install
        run: yarn
      - name: deploy
        run: yarn deploy
